name: Build Example

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
    
env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 8','platform=iOS Simulator,OS=15.5,name=iPhone X','platform=iOS Simulator,OS=15.5,name=iPhone 13','platform=iOS Simulator,OS=16.0,name=iPhone 14']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild clean build test -project "Example/Example.xcodeproj" -scheme "Example (iOS)" -sdk $TEST_SDK ONLY_ACTIVE_ARCH=NO | xcpretty
        env: 
         destination: ${{ matrix.destination }}
