on: push
name: watchOS example
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild clean build test -project "Example/Example.xcodeproj" -scheme Example -sdk $TEST_SDK ONLY_ACTIVE_ARCH=NO | xcpretty
        env: 
         destination: ${{ matrix.destination }}
