name: CI - Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: OversizeUI
    secrets: inherit
    
  build-iOS-example:
    name: Build iOS example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0', 'platform=iOS Simulator,name=iPad (10th generation),OS=18.0']
    with:
      path: Example/Example
      scheme: Example (iOS)
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  build-macOS-example:
    name: Build macOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    with:
      path: Example/Example
      scheme: Example (macOS)
      destination: platform=macOS,arch=arm64
    secrets: inherit
    
  build-tvOS-example:
    name: Build tvOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ['platform=tvOS Simulator,name=Apple TV 4K (3rd generation) (at 1080p),OS=18.0', 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=18.0']
    with:
      path: Example/Example
      scheme: Example (tvOS)
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  build-watchOS-example:
    name: Build watchOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ['platform=watchOS Simulator,name=Apple Watch Series 10 (42mm),OS=11.0']
    with:
      path: Example/Example
      scheme: Example (watchOS)
      destination: ${{ matrix.destination }}
    secrets: inherit
