name: CI - Pull Request
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: OversizeUI
    secrets: inherit
    
  build-iOS-example:
    name: Build iOS Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-ios-app.yml@main
    with:
      folder: Example
      project: Example
      scheme: Example (iOS)
    secrets: inherit

  build-examples:
    name: Build macOS, tvOS and watchOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ["platform=tvOS Simulator,name=Apple TV 4K", "platform=macOS,arch=x86_64", "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm"]
    with:
      folder: Example
      project: Example
      scheme: Example
      destination: ${{ matrix.destination }}
    secrets: inherit
