name: CI - Pull Request
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: OversizeUI
    secrets: inherit
    
  build-iOS-example:
    name: Build iOS Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-ios-app.yml@main
    with:
      folder: Example
      project: Example
      scheme: Example (iOS)
    secrets: inherit
    
  build-macOS-example:
    name: Build macOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    with:
      folder: Example
      project: Example
      scheme: Example (macOS)
      destination: platform=macOS,arch=arm64
    secrets: inherit
    
  build-tvOS-example:
    name: Build tvOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ["platform=tvOS Simulator,name=Apple TV 4K (3rd generation) (at 1080p),OS=17.2"]
    with:
      folder: Example
      project: Example
      scheme: Example (tvOS)
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  build-watchOS-example:
    name: Build watchOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ["platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm),OS=10.2"]
    with:
      folder: Example
      project: Example
      scheme: Example (watchOS)
      destination: platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm),OS=10.2
    secrets: inherit
