name: CI - Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeUI]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  build-iOS-example:
    name: Build iOS Example
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-ios-app.yml@main
    with:
      folder: Example
      app: Example (iOS)
    secrets: inherit
    
  build-macOS-example:
    name: Build macOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    with:
      folder: Example
      app: Example
      destination: platform=macOS,arch=x86_64
    secrets: inherit

  build-tvOS-example:
    name: Build tvOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ["platform=tvOS Simulator,name=Apple TV 4K"]
    with:
      folder: Example
      app: Example
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  build-watchOS-example:
    name: Build watchOS examples
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-app.yml@main
    strategy:
      matrix:
        destination: ['platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm']
    with:
      folder: Example
      app: Example
      destination: ${{ matrix.destination }}
    secrets: inherit

    
  bump:
    name: Bump version
    needs: [build-swiftpm, build-iOS-example, build-macOS-example, build-tvOS-example, build-watchOS-example]
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
    
  publish-docc:
    name: Publish docc
    needs: bump
    uses: ./.github/workflows/publish-docc.yml
    secrets: inherit

