name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.3.1,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild clean build test -project "Example/Example.xcodeproj" -scheme "Example (iOS)" -sdk $TEST_SDK ONLY_ACTIVE_ARCH=NO | xcpretty
        env: 
         destination: ${{ matrix.destination }}
