name: Publish DocC

on:
  push:
    branches: [ develop ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  documentation:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Generate DocC
      run: |
        mkdir -p docs
        set -o pipefail && xcodebuild docbuild \
          -scheme OversizeUI \
          -destination "generic/platform=iOS" \
          OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path --output-path docs" \
          | xcpretty
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: docc
        folder: docs
        target-folder: docs
        git-config-name: Mobile Automation
        git-config-email: alexander@oversize.design
        commit-message: Updated DocC documentation for version
